# Generated by Django 3.0.7 on 2020-09-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='TimesYouSaved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('when', models.DateField(verbose_name='When?')),
                ('how', models.TextField(max_length=255, verbose_name='How?')),
                ('thanks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person', verbose_name='Who you thank for')),
            ],
            options={
                'verbose_name': 'Time you saved',
                'verbose_name_plural': 'Times you saved',
            },
        ),
        migrations.CreateModel(
            name='TimesISaved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('when', models.DateField(verbose_name='When?')),
                ('how', models.TextField(max_length=255, verbose_name='How?')),
                ('thanks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person', verbose_name='Who I thank for')),
            ],
            options={
                'verbose_name': 'Time I saved',
                'verbose_name_plural': 'Times I saved',
            },
        ),
    ]
