# Generated by Django 3.0.7 on 2020-09-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesisaved',
            name='thanks',
        ),
        migrations.AddField(
            model_name='timesisaved',
            name='thanks',
            field=models.ManyToManyField(to='core.Person', verbose_name='Who I thank for'),
        ),
        migrations.RemoveField(
            model_name='timesyousaved',
            name='thanks',
        ),
        migrations.AddField(
            model_name='timesyousaved',
            name='thanks',
            field=models.ManyToManyField(to='core.Person', verbose_name='Who you thank for'),
        ),
    ]
